// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    XExamBoard: typeof import('./../components/x-exam-board.vue')['default']
    XExamInfo: typeof import('./../components/x-exam-info.vue')['default']
    XExamPic: typeof import('./../components/x-exam-pic.vue')['default']
    XExamSubject: typeof import('./../components/x-exam-subject.vue')['default']
  }
}
